# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Funk Force 5
email: kontakt@funkforce5.de
facebook_url: http://www.facebook.com/FunkForce5/
soundcloud_url: http://soundcloud.com/funkforce5
copyrightyear: 2017
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.funkforce5.de" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


gems: [jekyll-assets, github-pages, uglifier]

exclude: [build.sh, Gemfile, pyserve.bat, README.md]


assets:
    compress:
        js: uglifier
        css: sass
    
    assets:
      # photoswipe assets
      - "default-skin.png"
      - "default-skin.svg"
      - "preloader.gif"

    sources:
      - _assets/photoswipe